-- =====================================================================
-- Seed data — realistic mock data + ONE deliberate CAG-pattern conflict
-- Run AFTER 001_init_schema.sql and 002_rls_policies.sql
-- (as service_role / in Supabase SQL editor, since RLS would block
-- some of these inserts under a normal user session)
-- =====================================================================

-- ---------------------------------------------------------------------
-- Drugs
-- ---------------------------------------------------------------------
insert into drugs (id, name, manufacturer, gtin) values
  ('11111111-1111-1111-1111-111111111111', 'Paracetamol 500mg', 'Cipla Ltd', '08901234567892'),
  ('22222222-2222-2222-2222-222222222222', 'Amoxicillin 250mg', 'Sun Pharma', '08901234567908'),
  ('33333333-3333-3333-3333-333333333333', 'ORS Sachets', 'Zydus Lifesciences', '08901234567915'),
  ('44444444-4444-4444-4444-444444444444', 'Insulin Glargine', 'Biocon', '08901234567922'),
  ('55555555-5555-5555-5555-555555555555', 'Azithromycin 500mg', 'Cipla Ltd', '08901234567939');

-- ---------------------------------------------------------------------
-- Batches — normal, clean records
-- ---------------------------------------------------------------------
insert into batches (id, drug_id, batch_number, manufacture_date, expiry_date) values
  ('aaaaaaaa-0001-0001-0001-000000000001', '11111111-1111-1111-1111-111111111111', 'PCM-2025-A01', '2025-01-10', '2027-01-10'),
  ('aaaaaaaa-0001-0001-0001-000000000002', '22222222-2222-2222-2222-222222222222', 'AMX-2025-B02', '2025-02-15', '2027-02-15'),
  ('aaaaaaaa-0001-0001-0001-000000000003', '33333333-3333-3333-3333-333333333333', 'ORS-2025-C03', '2025-03-01', '2026-09-01'),
  ('aaaaaaaa-0001-0001-0001-000000000004', '44444444-4444-4444-4444-444444444444', 'INS-2025-D04', '2025-04-20', '2026-10-20'),
  ('aaaaaaaa-0001-0001-0001-000000000005', '55555555-5555-5555-5555-555555555555', 'AZI-2025-E05', '2025-05-05', '2027-05-05');

-- ---------------------------------------------------------------------
-- ⚠ THE CAG-PATTERN CONFLICT — demo centerpiece ⚠
-- Same drug + manufacturer + batch_number ('PCM-2025-A01', already
-- inserted above for Paracetamol/Cipla) re-entered with a DIFFERENT
-- expiry_date. This is exactly the bug CAG found 636 times in
-- e-Aushadhi. The anomaly engine (teammate 3) should catch this the
-- moment this second row (or an equivalent live scan) is written.
-- ---------------------------------------------------------------------
insert into batches (id, drug_id, batch_number, manufacture_date, expiry_date) values
  ('aaaaaaaa-0001-0001-0001-000000000099', '11111111-1111-1111-1111-111111111111', 'PCM-2025-A01', '2025-01-10', '2027-06-15');
  -- ^ same drug_id + batch_number as row 000000000001 above, but
  --   expiry_date is 2027-06-15 instead of 2027-01-10. This is the
  --   conflict to trigger live on stage.

-- ---------------------------------------------------------------------
-- Scan events — a normal factory→warehouse→hospital journey for one
-- clean batch, so the frontend has something to show in Logistics/Map
-- ---------------------------------------------------------------------
insert into scan_events (batch_id, node_type, node_id, location, raw_payload) values
  ('aaaaaaaa-0001-0001-0001-000000000001', 'factory', 'CIPLA-FACTORY-MUM', 'Mumbai, MH', '{"gtin":"08901234567892","batch":"PCM-2025-A01"}'),
  ('aaaaaaaa-0001-0001-0001-000000000001', 'warehouse', 'MH-STATE-WAREHOUSE-01', 'Pune, MH', '{"gtin":"08901234567892","batch":"PCM-2025-A01"}'),
  ('aaaaaaaa-0001-0001-0001-000000000001', 'hospital', 'DISTRICT-HOSPITAL-NASHIK', 'Nashik, MH', '{"gtin":"08901234567892","batch":"PCM-2025-A01"}');

-- ---------------------------------------------------------------------
-- Purchase orders
-- ---------------------------------------------------------------------
insert into purchase_orders (vendor_id, drug_id, quantity, status)
select id, '11111111-1111-1111-1111-111111111111', 5000, 'delivered'
from profiles where role = 'vendor' limit 1;
-- NOTE: run this after at least one 'vendor' profile exists (created
-- via Supabase Auth signup + a matching profiles row). If profiles is
-- still empty at seed time, comment this block out and re-run later.

-- ---------------------------------------------------------------------
-- NOTE on anomalies / ledger_entries:
-- These are intentionally NOT seeded directly here — they should be
-- generated by teammate 3's anomaly engine running against the
-- conflicting batch above (row ...099), so the demo shows the engine
-- actually catching it live rather than a pre-faked "already flagged"
-- row. See /ledger/src/demoSeed.js for the live-trigger version.
-- ---------------------------------------------------------------------
